// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snakeAndLadder/api/util.proto

package snakeAndLadder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameSetting struct {
	UserIds              []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	N                    int32    `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	SnakeCnt             int32    `protobuf:"varint,3,opt,name=snake_cnt,json=snakeCnt,proto3" json:"snake_cnt,omitempty"`
	LadderCnt            int32    `protobuf:"varint,4,opt,name=ladder_cnt,json=ladderCnt,proto3" json:"ladder_cnt,omitempty"`
	MaxStep              int32    `protobuf:"varint,5,opt,name=max_step,json=maxStep,proto3" json:"max_step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameSetting) Reset()         { *m = GameSetting{} }
func (m *GameSetting) String() string { return proto.CompactTextString(m) }
func (*GameSetting) ProtoMessage()    {}
func (*GameSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_f28e22cc1da29be2, []int{0}
}

func (m *GameSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameSetting.Unmarshal(m, b)
}
func (m *GameSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameSetting.Marshal(b, m, deterministic)
}
func (m *GameSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameSetting.Merge(m, src)
}
func (m *GameSetting) XXX_Size() int {
	return xxx_messageInfo_GameSetting.Size(m)
}
func (m *GameSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_GameSetting.DiscardUnknown(m)
}

var xxx_messageInfo_GameSetting proto.InternalMessageInfo

func (m *GameSetting) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *GameSetting) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *GameSetting) GetSnakeCnt() int32 {
	if m != nil {
		return m.SnakeCnt
	}
	return 0
}

func (m *GameSetting) GetLadderCnt() int32 {
	if m != nil {
		return m.LadderCnt
	}
	return 0
}

func (m *GameSetting) GetMaxStep() int32 {
	if m != nil {
		return m.MaxStep
	}
	return 0
}

type GameMeta struct {
	SnakeTails           []int32  `protobuf:"varint,1,rep,packed,name=snake_tails,json=snakeTails,proto3" json:"snake_tails,omitempty"`
	SnakeHeads           []int32  `protobuf:"varint,2,rep,packed,name=snake_heads,json=snakeHeads,proto3" json:"snake_heads,omitempty"`
	LadderTails          []int32  `protobuf:"varint,3,rep,packed,name=ladder_tails,json=ladderTails,proto3" json:"ladder_tails,omitempty"`
	LadderHeads          []int32  `protobuf:"varint,4,rep,packed,name=ladder_heads,json=ladderHeads,proto3" json:"ladder_heads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameMeta) Reset()         { *m = GameMeta{} }
func (m *GameMeta) String() string { return proto.CompactTextString(m) }
func (*GameMeta) ProtoMessage()    {}
func (*GameMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_f28e22cc1da29be2, []int{1}
}

func (m *GameMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMeta.Unmarshal(m, b)
}
func (m *GameMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMeta.Marshal(b, m, deterministic)
}
func (m *GameMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMeta.Merge(m, src)
}
func (m *GameMeta) XXX_Size() int {
	return xxx_messageInfo_GameMeta.Size(m)
}
func (m *GameMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMeta.DiscardUnknown(m)
}

var xxx_messageInfo_GameMeta proto.InternalMessageInfo

func (m *GameMeta) GetSnakeTails() []int32 {
	if m != nil {
		return m.SnakeTails
	}
	return nil
}

func (m *GameMeta) GetSnakeHeads() []int32 {
	if m != nil {
		return m.SnakeHeads
	}
	return nil
}

func (m *GameMeta) GetLadderTails() []int32 {
	if m != nil {
		return m.LadderTails
	}
	return nil
}

func (m *GameMeta) GetLadderHeads() []int32 {
	if m != nil {
		return m.LadderHeads
	}
	return nil
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f28e22cc1da29be2, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type UserRecord struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Steps                []int32  `protobuf:"varint,2,rep,packed,name=steps,proto3" json:"steps,omitempty"`
	Positions            []int32  `protobuf:"varint,3,rep,packed,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRecord) Reset()         { *m = UserRecord{} }
func (m *UserRecord) String() string { return proto.CompactTextString(m) }
func (*UserRecord) ProtoMessage()    {}
func (*UserRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f28e22cc1da29be2, []int{3}
}

func (m *UserRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRecord.Unmarshal(m, b)
}
func (m *UserRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRecord.Marshal(b, m, deterministic)
}
func (m *UserRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRecord.Merge(m, src)
}
func (m *UserRecord) XXX_Size() int {
	return xxx_messageInfo_UserRecord.Size(m)
}
func (m *UserRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UserRecord proto.InternalMessageInfo

func (m *UserRecord) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRecord) GetSteps() []int32 {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *UserRecord) GetPositions() []int32 {
	if m != nil {
		return m.Positions
	}
	return nil
}

type Visitor struct {
	// Types that are valid to be assigned to HasUserId:
	//	*Visitor_UserId
	HasUserId            isVisitor_HasUserId `protobuf_oneof:"has_user_id"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Visitor) Reset()         { *m = Visitor{} }
func (m *Visitor) String() string { return proto.CompactTextString(m) }
func (*Visitor) ProtoMessage()    {}
func (*Visitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f28e22cc1da29be2, []int{4}
}

func (m *Visitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visitor.Unmarshal(m, b)
}
func (m *Visitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visitor.Marshal(b, m, deterministic)
}
func (m *Visitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visitor.Merge(m, src)
}
func (m *Visitor) XXX_Size() int {
	return xxx_messageInfo_Visitor.Size(m)
}
func (m *Visitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Visitor.DiscardUnknown(m)
}

var xxx_messageInfo_Visitor proto.InternalMessageInfo

type isVisitor_HasUserId interface {
	isVisitor_HasUserId()
}

type Visitor_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*Visitor_UserId) isVisitor_HasUserId() {}

func (m *Visitor) GetHasUserId() isVisitor_HasUserId {
	if m != nil {
		return m.HasUserId
	}
	return nil
}

func (m *Visitor) GetUserId() string {
	if x, ok := m.GetHasUserId().(*Visitor_UserId); ok {
		return x.UserId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Visitor) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Visitor_UserId)(nil),
	}
}

func init() {
	proto.RegisterType((*GameSetting)(nil), "api.snakeAndLadder.GameSetting")
	proto.RegisterType((*GameMeta)(nil), "api.snakeAndLadder.GameMeta")
	proto.RegisterType((*Status)(nil), "api.snakeAndLadder.Status")
	proto.RegisterType((*UserRecord)(nil), "api.snakeAndLadder.UserRecord")
	proto.RegisterType((*Visitor)(nil), "api.snakeAndLadder.Visitor")
}

func init() {
	proto.RegisterFile("snakeAndLadder/api/util.proto", fileDescriptor_f28e22cc1da29be2)
}

var fileDescriptor_f28e22cc1da29be2 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0x6e, 0xe2, 0x30,
	0x18, 0xc4, 0x37, 0x40, 0xfe, 0x7d, 0x61, 0x57, 0x2b, 0x6b, 0xa5, 0x0d, 0x6a, 0x51, 0x69, 0x4e,
	0x9c, 0xe0, 0x80, 0xfa, 0x00, 0xa5, 0x87, 0x52, 0xa9, 0x5c, 0x42, 0x5b, 0xa9, 0xbd, 0x44, 0x2e,
	0xb6, 0xc0, 0x2a, 0x71, 0x22, 0xfb, 0x43, 0xe2, 0x25, 0x7a, 0xe9, 0x13, 0x57, 0xf9, 0x0c, 0x02,
	0x7a, 0x8b, 0x67, 0x26, 0xbf, 0x8c, 0x26, 0x86, 0xbe, 0xd5, 0xfc, 0x43, 0xde, 0x6a, 0xf1, 0xc8,
	0x85, 0x90, 0x66, 0xcc, 0x6b, 0x35, 0xde, 0xa2, 0xda, 0x8c, 0x6a, 0x53, 0x61, 0xc5, 0x18, 0xaf,
	0xd5, 0xe8, 0x3c, 0x92, 0x7d, 0x7a, 0x90, 0xdc, 0xf3, 0x52, 0x2e, 0x24, 0xa2, 0xd2, 0x2b, 0xd6,
	0x83, 0x68, 0x6b, 0xa5, 0x29, 0x94, 0xb0, 0xa9, 0x37, 0x68, 0x0f, 0xe3, 0x3c, 0x6c, 0xce, 0x0f,
	0xc2, 0xb2, 0x2e, 0x78, 0x3a, 0x6d, 0x0d, 0xbc, 0xa1, 0x9f, 0x7b, 0x9a, 0x5d, 0x40, 0x4c, 0xa8,
	0x62, 0xa9, 0x31, 0x6d, 0x93, 0x1a, 0x91, 0x70, 0xa7, 0x91, 0xf5, 0x01, 0x36, 0xc4, 0x27, 0xb7,
	0x43, 0x6e, 0xec, 0x94, 0xc6, 0xee, 0x41, 0x54, 0xf2, 0x5d, 0x61, 0x51, 0xd6, 0xa9, 0x4f, 0x66,
	0x58, 0xf2, 0xdd, 0x02, 0x65, 0x9d, 0x7d, 0x79, 0x10, 0x35, 0x7d, 0xe6, 0x12, 0x39, 0xbb, 0x82,
	0xc4, 0x7d, 0x03, 0xb9, 0xda, 0xb8, 0x3e, 0x7e, 0x0e, 0x24, 0x3d, 0x35, 0xca, 0x31, 0xb0, 0x96,
	0x5c, 0xd8, 0xb4, 0x75, 0x12, 0x98, 0x35, 0x0a, 0xbb, 0x86, 0xee, 0xbe, 0x88, 0x43, 0xb4, 0x29,
	0x91, 0x38, 0xcd, 0x31, 0x8e, 0x11, 0x07, 0xe9, 0x9c, 0x46, 0x88, 0x92, 0xdd, 0x40, 0xb0, 0x40,
	0x8e, 0x5b, 0xcb, 0x18, 0x74, 0x96, 0x95, 0x90, 0xa9, 0x47, 0xad, 0xe9, 0x99, 0xfd, 0x87, 0x50,
	0x1a, 0x53, 0x94, 0x76, 0x45, 0x3b, 0xc4, 0x79, 0x20, 0x8d, 0x99, 0xdb, 0x55, 0xf6, 0x0a, 0xf0,
	0x6c, 0xa5, 0xc9, 0xe5, 0xb2, 0x32, 0xa2, 0x89, 0xed, 0x97, 0xa5, 0xb7, 0xe3, 0x3c, 0x70, 0xc3,
	0xb2, 0x7f, 0xe0, 0x37, 0x4b, 0x1c, 0xea, 0xbb, 0x03, 0xbb, 0x84, 0xb8, 0xae, 0xac, 0x42, 0x55,
	0xe9, 0x43, 0xed, 0xa3, 0x90, 0x4d, 0x20, 0x7c, 0x51, 0x56, 0x61, 0x65, 0x58, 0xef, 0x07, 0x77,
	0xf6, 0xeb, 0x40, 0x9e, 0xfe, 0x86, 0x64, 0xcd, 0x6d, 0xb1, 0xb7, 0xa7, 0x7f, 0xdf, 0xfe, 0x9c,
	0xff, 0xfd, 0xf7, 0x80, 0x2e, 0xc6, 0xe4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x4f, 0x46, 0x7d,
	0x39, 0x02, 0x00, 0x00,
}
